eureka:
  client:
    registerWithEureka: true # 服务注册开关 fetchRegistry: true # 服务发现开关
    fetchRegistry: true #是否检索服务
    service-url:
      defaultZone: http://192.168.0.103:8081/eureka
server:
  port: 8082  #服务端口号
spring:
  application:
    name: service-client #服务名称--调用的时候根据名称来调用该服务的方法
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: zf