package com.cnbg.service.sample.sample.intf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-10T17:18:52.791+08:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://service.cnbg.com/sample/sample/intf", name = "Sample")
@XmlSeeAlso({com.cnbg.service.sample.sample.bean.ObjectFactory.class, com.cnbg.service.common.head.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Sample {

    @WebMethod(action = "/sample/sample")
    @WebResult(name = "SampleResponse", targetNamespace = "http://service.cnbg.com/sample/sample/bean", partName = "SampleResponse")
    public com.cnbg.service.sample.sample.bean.SampleResponse sample(

            @WebParam(partName = "SampleRequest", name = "SampleRequest", targetNamespace = "http://service.cnbg.com/sample/sample/bean")
                    com.cnbg.service.sample.sample.bean.SampleRequest sampleRequest
    );
}
