
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cnbg.service.sample.sample.intf;

import com.cnbg.service.common.head.RequestHeadDTO;
import com.cnbg.service.common.head.ResponseHeadDTO;
import com.cnbg.service.sample.sample.bean.SampleRequestDTO;
import com.cnbg.service.sample.sample.bean.SampleResponse;
import com.cnbg.service.sample.sample.bean.SampleResponseDTO;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-10T17:18:52.747+08:00
 * Generated source version: 3.3.6
 *
 */

@WebService(
                      serviceName = "SampleService",
                      portName = "SampleEndpoint",
                      targetNamespace = "http://service.cnbg.com/sample/sample/intf",
                      endpointInterface = "com.cnbg.service.sample.sample.intf.Sample")
public class SampleEndpointImpl implements Sample {

    private static final Logger LOG = Logger.getLogger(SampleEndpointImpl.class.getName());


    public com.cnbg.service.sample.sample.bean.SampleResponse sample(
            com.cnbg.service.sample.sample.bean.SampleRequest sampleRequest) {
        LOG.info("Executing operation sample");
        System.out.println(sampleRequest);
        try {
            RequestHeadDTO requestHead = sampleRequest.getRequestHead();
            String reqSeqNo = requestHead.getReqSeqNo();
            String serviceName = requestHead.getServiceName();
            String version = requestHead.getVersion();
            String consumerID = requestHead.getConsumerID();
            String providerID = requestHead.getProviderID();
            String sign = requestHead.getSign();

            SampleRequestDTO requestBody = sampleRequest.getRequestBody();
            String input1 = requestBody.getInput1();


            System.out.println(consumerID+providerID+reqSeqNo+"嘿嘿嘿");
            SampleResponse sampleResponse = new SampleResponse();


            ResponseHeadDTO responseHeadDTO = new ResponseHeadDTO();
            responseHeadDTO.setSeqNo("seqno");
            responseHeadDTO.setAppMessage("appmessage");
            responseHeadDTO.setAppCode("appcode");
            responseHeadDTO.setStatus(200);
            responseHeadDTO.setEsbCode("esbcode");
            responseHeadDTO.setReqSeqNo("reqseqno");

            SampleResponseDTO sampleResponseDTO = new SampleResponseDTO();
            sampleResponseDTO.setOutput1("output1");


            sampleResponse.setResponseHead(responseHeadDTO);
            sampleResponse.setResponseBody(sampleResponseDTO);
            return  sampleResponse;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
